create extension if not exists pgcrypto;

create table if not exists companies (id uuid primary key default gen_random_uuid(), name text not null, sector text, location text, created_at timestamptz not null default now());
create table if not exists projects (id uuid primary key default gen_random_uuid(), company_id uuid not null references companies(id) on delete cascade, name text not null, description text, methodology_version text not null default 'VITENUS-METHODOLOGY-0.1', status text not null default 'draft', created_at timestamptz not null default now());
create table if not exists data_sources (id uuid primary key default gen_random_uuid(), name text not null, source_type text not null, reference text, document_uri text, verified_at timestamptz, owner text, created_at timestamptz not null default now());
create table if not exists observations (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, variable_code text not null, value_numeric double precision, value_text text, unit text, period_start date, period_end date, source_id uuid references data_sources(id), collection_method text, quality_score integer check (quality_score between 1 and 5), verified boolean not null default false, notes text, created_at timestamptz not null default now());
create table if not exists opportunities (id uuid primary key default gen_random_uuid(), project_id uuid not null references projects(id) on delete cascade, name text not null, opportunity_type text, description text, baseline_definition text, future_state_definition text, status text not null default 'identified', regulatory_block boolean not null default false, safety_block boolean not null default false, technical_block boolean not null default false, critical_risk boolean not null default false, market_available boolean not null default true, supplier_available boolean not null default true, created_at timestamptz not null default now());
create table if not exists economic_cases (id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references opportunities(id) on delete cascade, capex numeric not null default 0, initial_costs numeric not null default 0, consulting_fee numeric not null default 0, other_eligible_costs numeric not null default 0, savings_material_annual numeric not null default 0, savings_waste_annual numeric not null default 0, savings_energy_annual numeric not null default 0, savings_water_annual numeric not null default 0, revenue_additional_annual numeric not null default 0, other_benefits_annual numeric not null default 0, opex_additional_annual numeric not null default 0, horizon_years integer not null default 5, hurdle_rate_percent numeric not null default 15, created_at timestamptz not null default now());
create table if not exists scores (id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references opportunities(id) on delete cascade, methodology_version text not null, ie numeric, ft numeric, ia numeric, ci numeric, tn numeric, gr numeric, ipc numeric, data_confidence numeric, roi_projected numeric, payback_months numeric, recommendation text, calculation_trace jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists performance_measurements (id uuid primary key default gen_random_uuid(), opportunity_id uuid not null references opportunities(id) on delete cascade, period_start date not null, period_end date not null, metric_code text not null, baseline_value numeric, actual_value numeric, unit text not null, source_id uuid references data_sources(id), verified boolean not null default false, notes text, created_at timestamptz not null default now());
create table if not exists methodology_versions (version_code text primary key, release_date date not null, status text not null, description text not null, assumptions jsonb not null default '{}'::jsonb);
create index if not exists idx_observations_project_variable on observations(project_id, variable_code);
create index if not exists idx_opportunities_project on opportunities(project_id);
create index if not exists idx_scores_opportunity on scores(opportunity_id);
create index if not exists idx_measurements_opportunity_period on performance_measurements(opportunity_id, period_start, period_end);

-- Production RLS policies must be added after the multi-tenant/auth model is defined.
-- Never expose a Supabase service_role key to the browser.
